name: Testing
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go: [1.16]
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          path: src/github.com/nats-io/nats-surveyor
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{matrix.go}}
      - name: Install deps
        shell: bash --noprofile --norc -x -eo pipefail {0}
        env:
          GO111MODULE: "on"
        run: |
          export GOPATH="$RUNNER_WORKSPACE"
          go get -v github.com/wadey/gocovmerge
          go get -v github.com/golangci/golangci-lint/cmd/golangci-lint
      - name: Lint
        shell: bash --noprofile --norc -x -eo pipefail {0}
        env:
          GO111MODULE: "on"
        run: |
          export GOPATH="$RUNNER_WORKSPACE"

          go vet ./...
          $(go env GOPATH)/bin/golangci-lint run \
             --no-config --exclude-use-default=false --max-same-issues=0 \
               --disable errcheck \
               --enable golint \
               --enable stylecheck \
               --enable interfacer \
               --enable unconvert \
               --enable gocyclo \
               --enable gofmt \
               --enable goimports \
               --enable misspell \
               --enable unparam \
               --enable nakedret \
               --enable prealloc \
               --enable scopelint \
               --enable gocritic \
               ./...

      - name: Run tests
        shell: bash --noprofile --norc -x -eo pipefail {0}
        env:
          GO111MODULE: "on"
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
        run: |
          export GOPATH="$RUNNER_WORKSPACE"

          go test -v -race -p 1 ./...
          ./scripts/cov.sh CI
